# Generated by Django 4.2.20 on 2025-04-09 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(upload_to='blog/covers/')),
                ('cover_alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo para imagen de portada')),
                ('excerpt', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('paragraph', 'Párrafo formateado (TinyMCE)'), ('raw_html', 'HTML personalizado'), ('image', 'Imagen'), ('heading', 'Encabezado'), ('quote', 'Cita'), ('code', 'Código')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo (accesibilidad)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Bloque de contenido',
                'verbose_name_plural': 'Bloques de contenido',
                'ordering': ['order'],
            },
        ),
    ]
