# Generated by Django 4.2.20 on 2025-04-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_entrada_seccion_delete_post_and_more'),
    ]

