# Generated by Django 4.2.20 on 2025-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
