# Generated by Django 4.2.20 on 2025-04-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_descri_page_m_descri_and_more'),
        ('blog', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='pagina',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_blog', to='page.page'),
        ),
    ]
