# Generated by Django 4.2.20 on 2025-04-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_entrada_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='pagina',
        ),
    ]
