# Generated by Django 4.2.20 on 2025-04-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_remove_entrada_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
