# Generated by Django 4.2.20 on 2025-04-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='estilo',
        ),
        migrations.AddField(
            model_name='page',
            name='m_conten',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='m_http_equiv',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='m_robots',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
