# Generated by Django 4.2.20 on 2025-04-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('registrado', 'Usuario Registrado'), ('moderador', 'Moderador'), ('administrador', 'Administrador')], default='registrado', max_length=15),
        ),
    ]
